"""Rendering a revision the way alembic does, and running the repo's own linter over it.

Shared by `test_alembic_template.py` (KAN-665: is the *template* clean?) and
`test_alembic_post_write_hooks.py` (KAN-692: does `alembic.ini`'s formatter clean up what the
*renderer* hands the template?). The two cards sit either side of one boundary and the second is
only meaningful against the first's fixtures, so the fixtures live here rather than being imported
across test modules.

No database and no `alembic revision` invocation: `template_to_file` with the same keyword
arguments `ScriptDirectory.generate_revision` passes is the whole of what the real command does to
this file. Note what that *excludes* — post-write hooks are run by `ScriptDirectory`, one layer
above `template_to_file`, so nothing here runs them by accident. `test_alembic_post_write_hooks.py`
runs them on purpose, and `tests/integration/test_alembic_autogenerate.py` drives the real command.
"""

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from alembic.util import format_as_comma, template_to_file

BACKEND = Path(__file__).resolve().parents[2]
TEMPLATE = BACKEND / "alembic" / "script.py.mako"
ALEMBIC_INI = BACKEND / "alembic.ini"
PYPROJECT = BACKEND / "pyproject.toml"

# What autogenerate hands the template for a migration that creates a table: rendered Python text
# for the bodies, plus any extra import lines the render needed. Copied in shape (not verbatim)
# from a real `alembic revision --autogenerate` run against a Postgres missing the `note` table.
AUTOGENERATED_UPGRADES = """op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget'))
    )"""
AUTOGENERATED_DOWNGRADES = "op.drop_table('widget')"
AUTOGENERATED_IMPORTS = "from sqlalchemy.dialects import postgresql"

# The same, with one column wide enough to overrun the 100-column limit — verbatim from that run.
WIDE_UPGRADES = """op.create_table('widget',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget'))
    )"""  # noqa: E501 — the point of this constant is that it is too long

# `note.search_vector` as alembic's renderer actually emits it, verbatim from KAN-692's run against
# a Postgres missing the `note` table. This is the overrun a formatter cannot repair: the line is
# 224 characters and the excess is inside one string literal, so `ruff format` can reflow the call
# around it and nothing more. Kept apart from WIDE_UPGRADES because the two behave differently
# under the hook, which is the whole point of having both.
WIDE_STRING_LITERAL_UPGRADES = """op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(body, '')), 'B')", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )"""  # noqa: E501 — as above


def render_revision(dest: Path, **kw: object) -> str:
    """Render the real template exactly as `ScriptDirectory.generate_revision` does."""
    template_to_file(
        TEMPLATE,
        dest,
        "utf-8",
        up_revision="a1b2c3d4e5f6",
        down_revision="0001",
        branch_labels=None,
        depends_on=None,
        create_date=datetime(2026, 1, 1, 12, 0, 0),
        comma=format_as_comma,
        message="a revision nobody has edited",
        **kw,
    )
    return dest.read_text(encoding="utf-8")


def ruff_check(path: Path) -> subprocess.CompletedProcess[str]:
    """Run the repo's own ruff configuration over a file outside the repo.

    `--config` is required because ruff discovers settings by walking up from the *file*, and the
    rendered revision lives in a tmp directory that knows nothing about `backend/pyproject.toml`.

    `sys.executable -m ruff` rather than a `PATH` lookup, for the same reason `alembic.ini`'s hook
    uses `type = module`: it resolves in the interpreter running the tests, which is the one that
    has ruff installed.
    """
    return subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--no-cache", "--output-format", "concise",
         "--config", str(PYPROJECT), str(path)],
        capture_output=True,
        text=True,
        check=False,
    )


def rule_codes(result: subprocess.CompletedProcess[str]) -> set[str]:
    """The distinct rule codes ruff reported, e.g. `{"E501"}`. Concise output is one per line."""
    return set(re.findall(r"^\S+?:\d+:\d+: ([A-Z]+\d+)", result.stdout, flags=re.MULTILINE))


def overlong_lines(result: subprocess.CompletedProcess[str], source: str) -> list[str]:
    """The source lines ruff reported E501 on, so a test can say *what* is still too long."""
    lines = source.splitlines()
    return [
        lines[int(n) - 1]
        for n in re.findall(r"^\S+?:(\d+):\d+: E501", result.stdout, flags=re.MULTILINE)
    ]
