"""`alembic.ini`'s `[post_write_hooks]` reflows what the renderer emits (KAN-692).

KAN-665 made a generated revision's *scaffolding* lint-clean. What it could not reach is the body:
autogenerate renders each `sa.Column(...)` on one line, and a wide one overruns E501 — nine
findings in the revision measured on KAN-692. `test_alembic_template.py`'s bottom test is the
positive control for that, and this file is the fix.

**Why a behavioural test and not "assert the section exists".** A config assertion proves the hook
is *declared*, which is the cheaper claim and the wrong one. `alembic/script/write_hooks.py`'s
`_run_hook` calls `subprocess.run` with no `check=`, so a hook whose command exits non-zero —
`formatt` instead of `format`, an unknown flag, a `--config` pointing nowhere — prints ruff's
complaint and generates the revision anyway. A declared-and-broken hook is therefore reachable, and
only running it can tell the two apart. (A missing *module* is the loud case: `CommandError`,
raised before any subprocess starts. Both halves are worth knowing; only one of them is safe.)

So this reads the real `alembic.ini`, takes the real hook list off it, and hands it to the same
`_run_hooks` that `ScriptDirectory` calls. That is one private name — the price of testing the
configuration rather than a paraphrase of it, and an `ImportError` if alembic ever renames it, which
is loud. `tests/integration/test_alembic_autogenerate.py` drives the whole public
`alembic revision --autogenerate` command against a real Postgres; this is the fast half, so
deleting the section reddens `make test` and the pre-push hook rather than only the Docker lane.

**One of the three tests exists because a mutation came back green.** `type = exec` /
`executable = ruff` passes everything else here and in the integration twin, because the suite runs
under `uv run` and so has the venv's `bin` on `PATH`. It is still the wrong mechanism, and
`test_the_hook_does_not_depend_on_path` is what tells the two apart.

**The limit, asserted rather than hoped for.** No formatter can break a long *string literal*.
`note.search_vector` renders as `sa.Computed("setweight(to_tsvector(...)) || ...", persisted=True)`
— 224 characters whose excess is one string — and `ruff format` reflows the call around it and
leaves the line long. The bottom test pins that, so nobody reads the hook as a total solution and
so the day ruff learns to split string literals is a red test with the news in it rather than a
silent improvement nobody notices.
"""

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script.write_hooks import _run_hooks
from alembic_render import (
    ALEMBIC_INI,
    AUTOGENERATED_DOWNGRADES,
    WIDE_STRING_LITERAL_UPGRADES,
    WIDE_UPGRADES,
    overlong_lines,
    render_revision,
    ruff_check,
    rule_codes,
)


def _run_the_configured_hooks(path: Path) -> None:
    """Run whatever `backend/alembic.ini` declares, through alembic's own dispatch."""
    _run_hooks(str(path), Config(str(ALEMBIC_INI)).get_hooks_list())


def test_the_hook_makes_a_wide_autogenerated_revision_lint_clean(tmp_path: Path) -> None:
    """The card, end to end at the fast layer: wide in, lint-clean out.

    The positive control is inside the test rather than borrowed from the file next door, because a
    guard that only fires through some other rule's success is not a guard: if the fixture ever
    stopped being over-long, "clean after the hook" would pass for want of anything to fix.
    """
    dest = tmp_path / "a1b2c3d4e5f6_wide.py"
    before = render_revision(dest, upgrades=WIDE_UPGRADES, downgrades=AUTOGENERATED_DOWNGRADES)

    assert rule_codes(ruff_check(dest)) == {"E501"}, (
        "positive control failed: the rendered revision was already clean, so the assertion below "
        f"proves nothing about the hook:\n{before}"
    )

    _run_the_configured_hooks(dest)

    after = dest.read_text(encoding="utf-8")
    result = ruff_check(dest)
    assert result.returncode == 0, (
        "the post-write hook declared in alembic.ini did not make the generated revision "
        "lint-clean. `ruff format` is what fixes E501 — `ruff check --fix` reports it and rewrites "
        f"nothing — and alembic swallows a hook that exits non-zero:\n{result.stdout}"
        f"{result.stderr}\n\nafter the hook:\n{after}"
    )
    assert after != before, "the hook ran but changed nothing, which is the swallowed-failure case"
    # It reflowed the call rather than deleting the migration: every argument survives.
    assert "server_default=sa.text(" in after
    assert "nullable=False" in after


def test_the_hook_does_not_depend_on_path(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """`type = module`, not `type = exec` — and this is the test that can tell them apart.

    Written because the `exec` mutation came back **green**. Swapping `type = module` /
    `module = ruff` for `type = exec` / `executable = ruff` passes every other assertion in this
    file and the integration twin, because the tests run under `uv run`, which puts
    `backend/.venv/bin` on `PATH`, so a `PATH` lookup for `ruff` happens to succeed. The guard was
    blind to the mechanism while claiming to protect the outcome.

    It is not equivalent. `backend/.venv/bin/alembic` is a normal way to invoke alembic — it is the
    entry point `uv sync` installs — and with a `PATH` that does not name the venv, `exec` dies with
    an uncaught `FileNotFoundError: 'ruff'` traceback *after* the revision file has been written,
    leaving an unformatted revision behind. Measured on KAN-692:
    `env PATH=/usr/bin:/bin .venv/bin/alembic revision --autogenerate` fails that way under `exec`
    and reformats the file under `module`, because `module` builds
    `[sys.executable, "-m", "ruff", ...]` and `sys.executable` is an absolute path.

    So: same wide revision, same configured hooks, but `PATH` pointed at an empty directory. Only
    an interpreter-resolved hook survives that.
    """
    empty_bin = tmp_path / "empty-bin"
    empty_bin.mkdir()
    monkeypatch.setenv("PATH", str(empty_bin))

    dest = tmp_path / "a1b2c3d4e5f6_no_path.py"
    before = render_revision(dest, upgrades=WIDE_UPGRADES, downgrades=AUTOGENERATED_DOWNGRADES)
    assert rule_codes(ruff_check(dest)) == {"E501"}, (
        f"positive control failed: the rendered revision was already clean:\n{before}"
    )

    _run_the_configured_hooks(dest)

    after = dest.read_text(encoding="utf-8")
    assert after != before, (
        "the hook did nothing with `ruff` absent from PATH. It must resolve ruff through the "
        "interpreter alembic is already running under (`type = module`), not through PATH "
        "(`type = exec`), or `backend/.venv/bin/alembic revision --autogenerate` from a shell that "
        "has not activated the venv writes an unformatted revision and then traces back."
    )
    assert ruff_check(dest).returncode == 0


def test_the_hook_cannot_break_a_long_string_literal(tmp_path: Path) -> None:
    """The honest boundary of the fix, so the hook is not mistaken for a total solution.

    `note.search_vector` is the real case: a `sa.Computed(...)` whose expression is one 130-odd
    character string. `ruff format` splits the surrounding call — which is a real improvement, and
    is asserted — but the literal itself stays on one line and E501 still names it. A revision that
    renders one still wants a hand wrap or an explicit `noqa`, and ruff reporting it is what stops
    that being a surprise at push time.
    """
    dest = tmp_path / "a1b2c3d4e5f6_computed.py"
    render_revision(
        dest, upgrades=WIDE_STRING_LITERAL_UPGRADES, downgrades=AUTOGENERATED_DOWNGRADES
    )

    _run_the_configured_hooks(dest)

    after = dest.read_text(encoding="utf-8")
    result = ruff_check(dest)
    still_long = overlong_lines(result, after)
    assert len(still_long) == 1, (
        f"expected exactly the string literal to survive, got {len(still_long)}:\n{after}"
    )
    # The one survivor is the literal, not a call the formatter failed to reflow.
    assert still_long[0].strip().startswith('"setweight(to_tsvector('), (
        f"the surviving long line is not the string literal, so something else went unformatted:"
        f"\n{still_long[0]}\n\nafter the hook:\n{after}"
    )
    # And the formatter did do its half: the call around it is now one argument per line.
    assert "sa.Computed(\n" in after
