"""A generated revision must be lint-clean as emitted (KAN-665).

Alembic's stock `script.py.mako` writes `from typing import Sequence, Union` and
`Union[str, Sequence[str], None]` annotations, and imports `op` and `sa` whether or not the body
uses them. Against the rules `backend/pyproject.toml` selects (E, F, I, UP, B, SIM) that is seven
findings in a file nobody has typed a character into yet. KAN-533 hand-edited its revision to get
green; the next person either repeats the edit or reaches for `--no-verify`.

`alembic/script.py.mako` is therefore a deliberate deviation from upstream, and a deviation with no
test is a deviation that gets "fixed" back the first time someone diffs it against a fresh
`alembic init`. This renders the real template the way alembic renders it and runs the real linter
over the result.

Two things are asserted rather than one, because the interesting failure mode of the fix is not the
lint. The template now emits `import sqlalchemy as sa` and `from alembic import op` only when the
rendered body refers to them — so the way to be lint-clean and *wrong* is to drop an import the
file still needs. Executing the rendered module catches that: module-level annotations are evaluated
at import time on 3.12, so a missing `Sequence` is a `NameError` here and not a surprise during
`alembic upgrade head`.

The fixtures and the ruff runner live in `alembic_render.py`, shared with
`test_alembic_post_write_hooks.py`. Neither this file nor that helper runs a post-write hook:
`template_to_file` is a layer below `ScriptDirectory`, which is what invokes them.

The bottom test is the boundary. `--autogenerate` renders each `sa.Column(...)` on a single line
and a wide one overruns E501 at this repo's line-length of 100. That text arrives from alembic's
autogenerate renderer, not from the template, so no edit here reaches it — KAN-692 fixed it in
`alembic.ini` instead, and that test is now the positive control the hook's own test consumes.
"""

from pathlib import Path

from alembic_render import (
    AUTOGENERATED_DOWNGRADES,
    AUTOGENERATED_IMPORTS,
    AUTOGENERATED_UPGRADES,
    WIDE_UPGRADES,
    render_revision,
    ruff_check,
    rule_codes,
)


def test_an_empty_revision_is_lint_clean_as_emitted(tmp_path: Path) -> None:
    """`alembic revision -m ...` — no autogenerate, so no body and no `op`/`sa` usage."""
    dest = tmp_path / "a1b2c3d4e5f6_empty.py"
    source = render_revision(dest)

    result = ruff_check(dest)

    assert result.returncode == 0, (
        "a freshly generated revision fails lint before anyone has edited it — that is the tax "
        f"KAN-665 removed:\n{result.stdout}{result.stderr}\n\nrendered:\n{source}"
    )


def test_an_autogenerated_revision_is_lint_clean_as_emitted(tmp_path: Path) -> None:
    """The `--autogenerate` shape: a body that uses `op` and `sa`, plus a dialect import."""
    dest = tmp_path / "a1b2c3d4e5f6_autogenerated.py"
    source = render_revision(
        dest,
        upgrades=AUTOGENERATED_UPGRADES,
        downgrades=AUTOGENERATED_DOWNGRADES,
        imports=AUTOGENERATED_IMPORTS,
    )

    result = ruff_check(dest)

    assert result.returncode == 0, (
        f"an autogenerated revision fails lint as emitted:\n{result.stdout}{result.stderr}"
        f"\n\nrendered:\n{source}"
    )


def test_the_rendered_revisions_import_everything_they_annotate(tmp_path: Path) -> None:
    """Lint-clean is not enough: the conditional imports must still cover what the file uses.

    Module-level annotations are evaluated at import on 3.12, so `str | Sequence[str] | None` with
    no `Sequence` in scope raises here — the one way trimming imports could be quietly wrong.
    """
    for name, kw in (
        ("empty", {}),
        (
            "autogenerated",
            {
                "upgrades": AUTOGENERATED_UPGRADES,
                "downgrades": AUTOGENERATED_DOWNGRADES,
                "imports": AUTOGENERATED_IMPORTS,
            },
        ),
    ):
        dest = tmp_path / f"a1b2c3d4e5f6_{name}.py"
        source = render_revision(dest, **kw)

        namespace: dict[str, object] = {}
        exec(compile(source, str(dest), "exec"), namespace)  # noqa: S102 — the file we just wrote

        assert namespace["revision"] == "a1b2c3d4e5f6"
        assert namespace["down_revision"] == "0001"
        # The bodies are defined but not called; calling `upgrade()` would need a live migration
        # context, which is `tests/integration`'s job.
        assert callable(namespace["upgrade"])
        assert callable(namespace["downgrade"])


def test_a_wide_autogenerated_column_still_overruns_e501_and_only_e501(tmp_path: Path) -> None:
    """The one part of the tax the *template* cannot remove, and the hook's positive control.

    `--autogenerate` renders every `sa.Column(...)` on one line, and a column with a timezone, a
    server default and a `nullable=` runs past 100 characters — revisions 0001 and 0003 have
    hand-wrapped columns for exactly this reason. The overrun is in text alembic's renderer
    produced, which the template only interpolates.

    KAN-665's version of this docstring said that wiring a formatter into `[post_write_hooks]`
    would empty this assertion, and that the test should then be deleted. KAN-692 wired the
    formatter up and this test **did not move** — which is the more useful fact, and is why it is
    still here: `template_to_file` is a layer below `ScriptDirectory`, and hooks are run by the
    latter. So the template's output is still exactly this wide, and the hook's own test
    (`test_alembic_post_write_hooks.py`) needs that to be true before it can claim to have fixed
    anything.

    `== {"E501"}` rather than "at least E501" on purpose: if it ever widens, the template regressed
    and this names the new code.
    """
    dest = tmp_path / "a1b2c3d4e5f6_wide.py"
    source = render_revision(dest, upgrades=WIDE_UPGRADES, downgrades=AUTOGENERATED_DOWNGRADES)

    assert rule_codes(ruff_check(dest)) == {"E501"}
    # Not merely "some line is long": the long line has to be the rendered column, or this control
    # would keep passing while the fixture drifted into something no formatter could reflow.
    assert any(len(line) > 100 and "sa.Column(" in line for line in source.splitlines()), (
        f"the fixture no longer renders an over-long sa.Column(...):\n{source}"
    )
