"""A generated revision must be lint-clean as emitted (KAN-665).

Alembic's stock `script.py.mako` writes `from typing import Sequence, Union` and
`Union[str, Sequence[str], None]` annotations, and imports `op` and `sa` whether or not the body
uses them. Against the rules `backend/pyproject.toml` selects (E, F, I, UP, B, SIM) that is seven
findings in a file nobody has typed a character into yet. KAN-533 hand-edited its revision to get
green; the next person either repeats the edit or reaches for `--no-verify`.

`alembic/script.py.mako` is therefore a deliberate deviation from upstream, and a deviation with no
test is a deviation that gets "fixed" back the first time someone diffs it against a fresh
`alembic init`. This renders the real template the way alembic renders it and runs the real linter
over the result.

Two things are asserted rather than one, because the interesting failure mode of the fix is not the
lint. The template now emits `import sqlalchemy as sa` and `from alembic import op` only when the
rendered body refers to them — so the way to be lint-clean and *wrong* is to drop an import the
file still needs. Executing the rendered module catches that: module-level annotations are evaluated
at import time on 3.12, so a missing `Sequence` is a `NameError` here and not a surprise during
`alembic upgrade head`.

No database and no `alembic revision` invocation: `template_to_file` with the same keyword arguments
`ScriptDirectory.generate_revision` passes is the whole of what the real command does to this file.

One thing the template cannot fix is pinned down at the bottom of this file: `--autogenerate`
renders each `sa.Column(...)` on a single line and a wide one overruns E501 at this repo's
line-length of 100. That text arrives from alembic's autogenerate renderer, not from the template,
so no edit here reaches it.
"""

import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from alembic.util import format_as_comma, template_to_file

BACKEND = Path(__file__).resolve().parents[2]
TEMPLATE = BACKEND / "alembic" / "script.py.mako"
PYPROJECT = BACKEND / "pyproject.toml"

# What autogenerate hands the template for a migration that creates a table: rendered Python text
# for the bodies, plus any extra import lines the render needed. Copied in shape (not verbatim)
# from a real `alembic revision --autogenerate` run against a Postgres missing the `note` table.
AUTOGENERATED_UPGRADES = """op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget'))
    )"""
AUTOGENERATED_DOWNGRADES = "op.drop_table('widget')"
AUTOGENERATED_IMPORTS = "from sqlalchemy.dialects import postgresql"

# The same, with one column wide enough to overrun the 100-column limit — verbatim from that run.
WIDE_UPGRADES = """op.create_table('widget',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget'))
    )"""  # noqa: E501 — the point of this constant is that it is too long


def _render(dest: Path, **kw: object) -> str:
    """Render the real template exactly as `ScriptDirectory.generate_revision` does."""
    template_to_file(
        TEMPLATE,
        dest,
        "utf-8",
        up_revision="a1b2c3d4e5f6",
        down_revision="0001",
        branch_labels=None,
        depends_on=None,
        create_date=datetime(2026, 1, 1, 12, 0, 0),
        comma=format_as_comma,
        message="a revision nobody has edited",
        **kw,
    )
    return dest.read_text(encoding="utf-8")


def _ruff(path: Path) -> subprocess.CompletedProcess[str]:
    """Run the repo's own ruff configuration over a file outside the repo.

    `--config` is required because ruff discovers settings by walking up from the *file*, and the
    rendered revision lives in a tmp directory that knows nothing about `backend/pyproject.toml`.
    """
    ruff = shutil.which("ruff") or str(Path(sys.executable).parent / "ruff")
    return subprocess.run(
        [ruff, "check", "--no-cache", "--output-format", "concise", "--config", str(PYPROJECT),
         str(path)],
        capture_output=True,
        text=True,
        check=False,
    )


def _rule_codes(result: subprocess.CompletedProcess[str]) -> set[str]:
    """The distinct rule codes ruff reported, e.g. `{"E501"}`. Concise output is one per line."""
    return set(re.findall(r"^\S+?:\d+:\d+: ([A-Z]+\d+)", result.stdout, flags=re.MULTILINE))


def test_an_empty_revision_is_lint_clean_as_emitted(tmp_path: Path) -> None:
    """`alembic revision -m ...` — no autogenerate, so no body and no `op`/`sa` usage."""
    dest = tmp_path / "a1b2c3d4e5f6_empty.py"
    source = _render(dest)

    result = _ruff(dest)

    assert result.returncode == 0, (
        "a freshly generated revision fails lint before anyone has edited it — that is the tax "
        f"KAN-665 removed:\n{result.stdout}{result.stderr}\n\nrendered:\n{source}"
    )


def test_an_autogenerated_revision_is_lint_clean_as_emitted(tmp_path: Path) -> None:
    """The `--autogenerate` shape: a body that uses `op` and `sa`, plus a dialect import."""
    dest = tmp_path / "a1b2c3d4e5f6_autogenerated.py"
    source = _render(
        dest,
        upgrades=AUTOGENERATED_UPGRADES,
        downgrades=AUTOGENERATED_DOWNGRADES,
        imports=AUTOGENERATED_IMPORTS,
    )

    result = _ruff(dest)

    assert result.returncode == 0, (
        f"an autogenerated revision fails lint as emitted:\n{result.stdout}{result.stderr}"
        f"\n\nrendered:\n{source}"
    )


def test_the_rendered_revisions_import_everything_they_annotate(tmp_path: Path) -> None:
    """Lint-clean is not enough: the conditional imports must still cover what the file uses.

    Module-level annotations are evaluated at import on 3.12, so `str | Sequence[str] | None` with
    no `Sequence` in scope raises here — the one way trimming imports could be quietly wrong.
    """
    for name, kw in (
        ("empty", {}),
        (
            "autogenerated",
            {
                "upgrades": AUTOGENERATED_UPGRADES,
                "downgrades": AUTOGENERATED_DOWNGRADES,
                "imports": AUTOGENERATED_IMPORTS,
            },
        ),
    ):
        dest = tmp_path / f"a1b2c3d4e5f6_{name}.py"
        source = _render(dest, **kw)

        namespace: dict[str, object] = {}
        exec(compile(source, str(dest), "exec"), namespace)  # noqa: S102 — the file we just wrote

        assert namespace["revision"] == "a1b2c3d4e5f6"
        assert namespace["down_revision"] == "0001"
        # The bodies are defined but not called; calling `upgrade()` would need a live migration
        # context, which is `tests/integration`'s job.
        assert callable(namespace["upgrade"])
        assert callable(namespace["downgrade"])


def test_a_wide_autogenerated_column_still_overruns_e501_and_only_e501(tmp_path: Path) -> None:
    """The one part of the tax the template cannot remove, written down so it is not rediscovered.

    `--autogenerate` renders every `sa.Column(...)` on one line, and a column with a timezone, a
    server default and a `nullable=` runs past 100 characters — revision 0001's columns are
    hand-wrapped for exactly this reason. The overrun is in text alembic's renderer produced, which
    the template only interpolates, so a wide migration still wants a reflow by hand.

    The assertion is `== {"E501"}` rather than "at least E501" on purpose: if it ever widens, the
    template regressed and this names the new code. If it ever empties — someone wired up a
    formatter as an alembic `post_write_hooks`, which is the proper fix and is out of KAN-665's
    scope — delete this test and say so.
    """
    dest = tmp_path / "a1b2c3d4e5f6_wide.py"
    _render(dest, upgrades=WIDE_UPGRADES, downgrades=AUTOGENERATED_DOWNGRADES)

    assert _rule_codes(_ruff(dest)) == {"E501"}
