## -----------------------------------------------------------------------------------------------
##  DELIBERATE DEVIATION FROM ALEMBIC'S STOCK TEMPLATE (KAN-665). Please do not "restore" it.
##
##  Lines starting `##` are Mako comments and never reach a generated revision, so this note costs
##  nothing at runtime. Two syntaxes below look like ordinary text and are easy to break while
##  editing the Python around them: `${...}` is interpolation, and `<% ... %>` is a Python block
##  whose assignments are then visible to the interpolations that follow it.
##
##  `backend/pyproject.toml` selects ruff's E, F, I, UP, B and SIM. Alembic's stock
##  `templates/generic/script.py.mako` — still unchanged as of alembic 1.18.5, so this is ours to
##  carry rather than something to wait upstream out on — emits a file that fails four of those
##  checks (7 findings) before anyone has written a line of migration:
##
##    UP035  `from typing import Sequence` — `collections.abc` is the 3.12 home
##    UP007  `Union[str, Sequence[str], None]` × 3 — PEP 604 `X | Y` is the required spelling
##    I001   `from alembic import op` above `import sqlalchemy as sa` — isort sorts plain
##           `import` statements ahead of `from` imports inside the third-party block
##    F401   `op` and `sa` imported and never used, which is every revision whose body is written
##           by hand (`alembic revision -m ...`) rather than autogenerated
##
##  KAN-533 hand-edited its output to get green. That tax is per-revision and compounding, and the
##  cheap way out of it is `git push --no-verify` — the one habit this repo cannot afford.
##
##  What this template CANNOT fix, so that nobody spends an afternoon trying: E501. Autogenerate
##  renders each `sa.Column(...)` onto a single line and a wide one runs past 100 characters — see
##  revision 0001, whose columns are hand-wrapped for precisely that reason. That text arrives from
##  alembic's renderer already formatted and this file only interpolates it. The real fix is a
##  formatter wired into `[post_write_hooks]` in `alembic.ini`, which KAN-665 left alone; the
##  boundary is pinned by `tests/unit/test_alembic_template.py`.
##
##  What follows is, near enough, what `ruff check --fix` makes of the stock template: we deviate
##  only where a selected rule forces it. In particular the string literals are still `repr()`'s
##  single quotes even though the rest of the repo writes double, because no selected rule cares
##  and every line kept identical to upstream is one line less to reconcile when alembic's own
##  template eventually moves.
##
##  Note the annotations keep alembic's full `str | Sequence[str] | None` rather than narrowing to
##  the `str | None` that revision 0001 happens to spell. `alembic merge` renders a *tuple* into
##  `down_revision` using this same template, and `branch_labels` is a tuple whenever it is set at
##  all; the narrow spelling is true of 0001 and false of the general case. The card was about how
##  the type is spelled, not about what it means.
## -----------------------------------------------------------------------------------------------
<%
    # Which of `op` and `sa` this revision actually uses. `upgrades` and `downgrades` arrive from
    # autogenerate as already-rendered Python text, so the body itself is the honest answer, and a
    # plain `alembic revision -m ...` leaves both empty and therefore imports neither. Emitting the
    # pair unconditionally is exactly what trips F401 — and F401 cannot be suppressed here without
    # also suppressing the genuinely unused import someone leaves behind later.
    #
    # The heuristic cannot fail quietly. If you write a body by hand afterwards and the import is
    # missing, ruff's F821 (undefined name, part of the selected F block) names it on the same
    # pre-push run that a stock-template revision used to fail.
    body = "%s\n%s" % (upgrades or "", downgrades or "")

    stdlib_imports = ["from collections.abc import Sequence"]

    third_party_imports = []
    if "sa." in body:
        third_party_imports.append("import sqlalchemy as sa")
    if "op." in body:
        third_party_imports.append("from alembic import op")
    if imports:
        # Autogenerate's own extras — `from sqlalchemy.dialects import postgresql` and friends.
        # Appending keeps isort satisfied for `from` imports, since `alembic` sorts before
        # `sqlalchemy`. A third-party *plain* `import x` would land out of order here; ruff I001
        # says so rather than letting it through, which is the outcome we want from a guess.
        third_party_imports.append(imports)

    import_block = "\n".join(stdlib_imports)
    if third_party_imports:
        import_block += "\n\n" + "\n".join(third_party_imports)
%>"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

${import_block}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | Sequence[str] | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Upgrade schema."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Downgrade schema."""
    ${downgrades if downgrades else "pass"}
