"""note_link: the wikilink edge table

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-17

KAN-562 (SLICES §V5 step 2, built on KAN-561's ``[[...]]`` parser). One table, ``note_link``: one
row per wikilink a note's body currently contains, reconciled on every save by
``app/note_links.py``. **This migration adds schema only — nothing here talks to pandan, and
nothing populates the table for notes that already exist.** A pre-existing note's edges appear the
first time its body is saved again after this migration runs, because the reconcile pass is a
save-time operation, not a backfill; a note nobody edits again simply has no rows here until it is.
That is consistent with the rest of the card (ADR 0003 — no network call anywhere in this path) and
is a corner worth knowing about at rollout: a *fresh* deployment that runs this migration and then
never re-saves any pre-existing notes will show `/links` (KAN-566, not yet built) as empty for notes
that visibly contain ``[[KAN-…]]`` in their prose, until each one is opened and saved once more.

**Four columns, argued in full in ``app/models/note_link.py``** — this migration mirrors that
model's shape rather than re-arguing it:

- ``source_note_id`` — ``note.id``, ``ON DELETE CASCADE``. An edge has no meaning independent of the
  note whose body it came from, so deleting that note takes its outbound edges with it. Unlike
  ``note.owner_id → user``'s ``RESTRICT``, there is no cleanup job for which "the note is gone but
  its edges remain" is a state worth protecting.
- ``target_kind`` — ``VARCHAR(16)``, not a Postgres ``ENUM``. Widening an enum is itself a
  migration; a plain string lets KAN-563's future ``"NOTE"`` kind arrive as a value.
- ``target_ref`` — ``VARCHAR(255)``, matching ``NoteCreate.title``'s own limit rather than a pandan
  ref's few characters, because a future ``NOTE``-kind edge stores a title here.
- ``resolved_id`` — nullable ``INTEGER``, no foreign key (which table it would name depends on
  ``target_kind``, and one constraint cannot express that). Always ``NULL`` out of this card;
  KAN-564 is the card that ever writes to it.

**The unique constraint over ``(source_note_id, target_kind, target_ref)`` is the edge's identity**,
and it is what makes "leave an unchanged edge's row untouched" a real operation rather than an
aspiration: without it, two saves that both produce the wikilink set ``{KAN-1}`` have nothing to
compare "this row" against, and the only implementation left is delete-and-reinsert — which would
reset ``resolved_id`` (and any timestamp KAN-564 adds) on every save regardless of whether that
particular edge changed at all. It also collapses repeated occurrences of the same target within one
body (``[[KAN-1]]`` written twice) to the one edge that relationship actually is.

**No separate index on ``source_note_id``.** The unique constraint above is a composite index with
``source_note_id`` as its leading column, and Postgres can answer "every edge for this note" — the
reconciler's one read — from that column prefix alone. A second single-column index would just be a
second structure to maintain on every insert and delete for a query the first one already serves.

Hand-written rather than autogenerated, following migration ``0002``'s precedent: the DDL below is
straightforward enough that autogenerate would produce very nearly this, but the naming and
comments read better authored than diffed. Unlike ``0002`` there is no generated-column trap here —
every column is ordinary — so, unlike that migration, this one *is* something an autogenerate
re-run should reproduce with an empty diff, which is what
``tests/integration/test_alembic.py::test_autogenerate_would_not_drop_anything`` checks.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | None = None
depends_on: str | None = None

TARGET_KIND_MAX = 16
TARGET_REF_MAX = 255
"""Byte-for-byte ``app/models/note_link.py``'s ``TARGET_KIND_MAX`` / ``TARGET_REF_MAX``. Duplicated
rather than imported, the same direction migration ``0002`` already draws against the model: a
migration describes the schema at one moment in history and must keep working after the model has
moved on."""


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "note_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_note_id", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(length=TARGET_KIND_MAX), nullable=False),
        sa.Column("target_ref", sa.String(length=TARGET_REF_MAX), nullable=False),
        sa.Column("resolved_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_note_id"],
            ["note.id"],
            name=op.f("fk_note_link_source_note_id_note"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_link")),
        sa.UniqueConstraint(
            "source_note_id",
            "target_kind",
            "target_ref",
            name=op.f("uq_note_link_source_note_id"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema. One table, one drop — the unique constraint and the foreign key go with
    it, so there is nothing to drop separately the way migration ``0002`` has to for its index."""
    op.drop_table("note_link")
