"""note_version: the version history table

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-01

R13 (``docs/roadmap/BREADBOARD.md``), KAN-1064. One table, ``note_version``: one row per body a
note's `POST`/`PATCH` ever wrote, cut by ``app/note_versions.py``'s ``cut_version`` inside the same
transaction as the save. **This migration adds schema only** — no backfill, and none is possible: a
version is a snapshot taken *at* save time, so a note that existed before this migration ran has no
history until the next time its body is saved, exactly the same rollout corner migration `0003`
records for `note_link` and for the identical reason (a reconcile-on-save table cannot retroactively
know what a save it never saw wrote).

**Three columns, argued in full in ``app/models/note_version.py``** — this migration mirrors that
model's shape rather than re-arguing it:

- ``note_id`` — ``note.id``, ``ON DELETE CASCADE``. A version has no meaning independent of the note
  it is a snapshot of, so deleting the note takes its whole history with it — the identical choice
  migration ``0003`` makes for ``note_link.source_note_id``, for the identical reason.
- ``body`` — ``TEXT``, unbounded, matching ``note.body``: a length cap on prose is a cap on the
  product, and a version is exactly as long as the body it was cut from.
- ``created_at`` — ``TIMESTAMPTZ``, defaulting to ``now()``, when this snapshot was cut.

**No ``owner_id`` and no index beyond the primary key**, both argued in the model's own docstring:
the table is reached only by joining through a note id that has already been authorized, and every
read this card makes is ``WHERE note_id = :note_id``, one note at a time, which does not yet earn a
second structure to maintain on every write.

Generated by ``alembic revision --autogenerate`` against a live Postgres 17 with every model
imported (the empty diff on the three existing tables is what proves this migration adds *only*
`note_version`), then hand-annotated the way migration ``0003`` was — the DDL below is exactly what
autogenerate produced, so ``tests/integration/test_alembic.py``'s
``test_autogenerate_would_not_drop_anything`` is expected to see an empty diff against it, the same
property that migration already pins for ``note_link``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "note_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
            name=op.f("fk_note_version_note_id_note"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_version")),
    )


def downgrade() -> None:
    """Downgrade schema. One table, one drop — the foreign key goes with it, so there is nothing to
    drop separately the way migration ``0002`` has to for its index."""
    op.drop_table("note_version")
