"""attachment: the object storage table

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-01

R14 (``docs/roadmap/BREADBOARD.md``), KAN-1067/1068/1069. One table, ``attachment``: one row per
uploaded file, created by ``POST /api/v1/notes/{ref}/attachments`` and read back by
``GET /api/v1/notes/{ref}/attachments/{id}`` (``app/api/attachments.py``). **Schema only** — this
migration talks to no object storage and creates no bucket; a real R2 bucket and credentials are a
manual step for the maintainer's own Cloudflare account, outside any PR's scope.

Autogenerated against a live Postgres 17 and then hand-annotated, following migration ``0003``'s
own precedent (hand-written DDL that autogenerate would reproduce with an empty diff) rather than
its "hand-written from scratch" one — this table has no generated-column trap and no sequence
Alembic can't see, so the generated DDL needed no correction, only the comments below.

**Shape, argued in full in ``app/models/attachment.py``** — this migration mirrors that model
rather than re-arguing it:

- ``note_id`` — ``note.id``, ``ON DELETE CASCADE``. An attachment has no meaning independent of the
  note it was uploaded to, matching ``note_link.source_note_id``'s reasoning in migration ``0003``
  exactly. ``ix_attachment_note_id`` exists because, unlike ``note_link``'s unique constraint, there
  is no other index on this table whose leading column already answers "every attachment for this
  note".
- ``r2_key`` — ``VARCHAR(512)``, unique. The object's address inside the bucket
  (``{note_id}/{uuid4}{ext}``, ``app/api/attachments.py``'s ``object_key``), never the caller's
  filename — see that function for why a filename would be a path-traversal-shaped key.
- ``content_type`` — ``VARCHAR(255)``, the caller-supplied MIME type at upload time.
- ``size_bytes`` — ``BIGINT``, not the plain ``INTEGER`` ``note.id`` uses: a note body is bounded by
  what a person types, an attachment is not, and a 2 GiB ceiling is cheap to avoid paying for later.

``attachment`` has **no ``owner_id`` column**, by design (CLAUDE.md's owner-scoping rule, and
``app/models/attachment.py``'s module docstring): the only path from a row here to an owner is
``note_id -> note.owner_id``, and every route on this table is reached through ``NoteFromRef``
(``app/api/refs.py``), which has already made that check before either route in
``app/api/attachments.py`` runs a query against this table.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

R2_KEY_MAX = 512
CONTENT_TYPE_MAX = 255
"""Byte-for-byte ``app/models/attachment.py``'s ``R2_KEY_MAX``/``CONTENT_TYPE_MAX``, duplicated
rather than imported — the same direction migrations ``0002``/``0003`` already draw against their
models: a migration describes the schema at one moment in history and must keep working after the
model has moved on."""


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("r2_key", sa.String(length=R2_KEY_MAX), nullable=False),
        sa.Column("content_type", sa.String(length=CONTENT_TYPE_MAX), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
            name=op.f("fk_attachment_note_id_note"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
        sa.UniqueConstraint("r2_key", name=op.f("uq_attachment_r2_key")),
    )
    op.create_index(op.f("ix_attachment_note_id"), "attachment", ["note_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema. The index goes first — the FK and unique constraint drop with the table,
    same as migration ``0003``'s downgrade."""
    op.drop_index(op.f("ix_attachment_note_id"), table_name="attachment")
    op.drop_table("attachment")
