"""team mirror, and note.team_id

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-03

R16 (``docs/roadmap/BREADBOARD.md``), KAN-1082, ADR 0011 — the schema half of team-scoped notes.
Two changes, both additive:

- ``team`` — the mirror of pandan's team, existing purely so ``note.team_id`` has a row to point at.
  **One column, on purpose** (``app/models/team.py``'s module docstring argues this in full): a
  name, a role list, or anything else pandan owns would go stale, the same reasoning migration
  ``0001`` already applied to ``user``. ``id`` has no default, matching ``user.id`` — the value is
  pandan's UUID, supplied by whichever later card (R16.2/R16.5) JIT-inserts the row.
- ``note.team_id`` — nullable ``FK -> team.id``, ``ON DELETE RESTRICT``. Every existing note gets
  ``team_id = NULL``, i.e. today's behavior, byte-for-byte — the same consequence pandan's own ADR
  0021 recorded for ``board.team_id``. ``RESTRICT`` rather than ``SET NULL``: a locally mirrored
  ``team`` row is not the authority on whether a note's team association should end (matching
  ``owner_id``'s own ``RESTRICT`` reasoning exactly), so a future cleanup job that prunes stale team
  mirrors fails loudly instead of silently converting a team-shared note into a personal one.

**Schema only.** No route, no resolver, no authorization change lands in this migration — those are
R16.2/R16.3/R16.5. A note cannot actually be given a `team_id` yet, since nothing JIT-inserts a
`team` row for the foreign key to satisfy; that begins with R16.2.

Autogenerated against a live Postgres 17 and then hand-annotated, following migration ``0005``'s
own precedent — no generated-column trap and no sequence here, so the generated DDL needed no
correction.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.add_column("note", sa.Column("team_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_note_team_id"), "note", ["team_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_note_team_id_team"),
        "note",
        "team",
        ["team_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    """Downgrade schema. Reverse order: the FK and index on `note` drop before `team`, since `team`
    cannot be dropped while `note.team_id` still references it."""
    op.drop_constraint(op.f("fk_note_team_id_team"), "note", type_="foreignkey")
    op.drop_index(op.f("ix_note_team_id"), table_name="note")
    op.drop_column("note", "team_id")
    op.drop_table("team")
