"""kaya_account, kaya_oauth_account, kaya_session: fastapi-users tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25

ADR 0012, KAN-1738 — the schema half of kaya's own authorization server. Three additive tables,
none of them touching anything that exists today:

- ``kaya_account`` — a human who has logged into kaya directly via GitHub OAuth. **Not** the
  existing ``user`` table (migration ``0001``): that one is the pandan-mirror ADR 0002 built, still
  load-bearing for every existing note's ``owner_id`` until a later card reconciles the two. `id`
  is fastapi-users' own ``uuid4`` default, minted here — the opposite of ``user.id``'s contract,
  which takes pandan's id verbatim and mints nothing.
- ``kaya_oauth_account`` — one row per linked OAuth provider (today, only ``"github"``),
  `ON DELETE CASCADE` from ``kaya_account`` — deleting the account deletes its linked logins, there
  being nothing else to point them at.
- ``kaya_session`` — the ``DatabaseStrategy`` table: one row per live cookie session, `ON DELETE
  CASCADE` from ``kaya_account``. Deleting a row is the entire logout mechanism (instant
  revocation, no token to wait out an expiry on).

**Schema only**, mirroring migration ``0006``'s own precedent: no route depends on these tables
existing yet (`app/identity/router.py`'s docstring is explicit that no note/team/attachment route
is wired to this identity until KAN-1740). Autogenerated against a live Postgres 17
(`COMPOSE_PROJECT_NAME=kaya-kan1738 KAYA_DB_PORT=5439 make db`) and hand-annotated; the only
correction needed was adding the ``fastapi_users_db_sqlalchemy`` import autogenerate's own
``GUID``/``TIMESTAMPAware`` column types reference but never imports on their own.
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "kaya_account",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kaya_account")),
    )
    op.create_index(op.f("ix_kaya_account_email"), "kaya_account", ["email"], unique=True)
    op.create_table(
        "kaya_oauth_account",
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("oauth_name", sa.String(length=100), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("account_id", sa.String(length=320), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kaya_account.id"],
            name=op.f("fk_kaya_oauth_account_user_id_kaya_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kaya_oauth_account")),
    )
    op.create_index(
        op.f("ix_kaya_oauth_account_account_id"), "kaya_oauth_account", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_kaya_oauth_account_oauth_name"), "kaya_oauth_account", ["oauth_name"], unique=False
    )
    op.create_table(
        "kaya_session",
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kaya_account.id"],
            name=op.f("fk_kaya_session_user_id_kaya_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_kaya_session")),
    )
    op.create_index(op.f("ix_kaya_session_created_at"), "kaya_session", ["created_at"], unique=False)


def downgrade() -> None:
    """Downgrade schema. Reverse order: ``kaya_oauth_account``/``kaya_session`` drop before
    ``kaya_account``, since both carry a `FOREIGN KEY` into it."""
    op.drop_index(op.f("ix_kaya_session_created_at"), table_name="kaya_session")
    op.drop_table("kaya_session")
    op.drop_index(op.f("ix_kaya_oauth_account_oauth_name"), table_name="kaya_oauth_account")
    op.drop_index(op.f("ix_kaya_oauth_account_account_id"), table_name="kaya_oauth_account")
    op.drop_table("kaya_oauth_account")
    op.drop_index(op.f("ix_kaya_account_email"), table_name="kaya_account")
    op.drop_table("kaya_account")
