"""personal_access_token: kaya's own PAT table

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-25

ADR 0012, KAN-1739 — the `kaya_pat_…` self-serve agent token, mirroring pandan ADR 0014. One
additive table, `ON DELETE CASCADE` from `kaya_account` (migration `0007`): deleting an account
revokes every token it minted. `scope` carries the `read`/`write` split ADR 0012 calls for
verbatim; nothing enforces it yet (that's `KAN-1740`, when a PAT bearer is wired into request
authentication) — the column and its `CHECK` exist first so that enforcement has somewhere to read
from, the same "schema only" sequencing migration `0006` used for `note.team_id`.

**Schema only, same precedent as `0006`/`0007`.** No route depends on this table existing yet;
`app/api/tokens.py`'s own CRUD is gated on kaya's *cookie-session* identity (`KAN-1738`), never a
PAT bearer, so this migration changes nothing about how any existing request is authenticated.

Autogenerated against a live Postgres 17 (`COMPOSE_PROJECT_NAME=kaya-kan1739 KAYA_DB_PORT=5440
make db`) and hand-annotated. Two corrections: adding the `fastapi_users_db_sqlalchemy` import
autogenerate references but never imports (same gap migration `0007` hit), and an earlier draft of
the model's `CheckConstraint` passed the fully-built name (`ck_personal_access_token_scope`) as
`name=`, which `app/models/base.py`'s naming convention then re-prefixed into
`ck_personal_access_token_ck_personal_access_token_scope` — caught by re-diffing before this file
was written, not left for a follow-up.
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "personal_access_token",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_prefix", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=16), server_default="write", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scope IN ('read', 'write')", name=op.f("ck_personal_access_token_scope")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kaya_account.id"],
            name=op.f("fk_personal_access_token_user_id_kaya_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_access_token")),
    )
    op.create_index(
        op.f("ix_personal_access_token_token_hash"),
        "personal_access_token",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_personal_access_token_user_id"), "personal_access_token", ["user_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_personal_access_token_user_id"), table_name="personal_access_token")
    op.drop_index(op.f("ix_personal_access_token_token_hash"), table_name="personal_access_token")
    op.drop_table("personal_access_token")
