"""pandan_link: a kaya account's linked pandan credential

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-25

ADR 0012's amendment (KAN-1741). One additive table, `ON DELETE CASCADE` from `kaya_account`
(migration `0007`), unique on `user_id` — at most one linked pandan account per kaya account. See
`app/identity/pandan_link.py`'s module docstring for the full "why this table exists at all" (the
board-embed preview used to free-ride on the same PAT authenticating both apps; `KAN-1740` ended
that) and for why `encrypted_token` is reversibly encrypted rather than hashed the way
`personal_access_token.token_hash` is — kaya must hand pandan back the raw secret on every embed
render, so a one-way hash cannot work here.

**Schema only, same precedent as `0006`/`0007`/`0008`.** No existing route or row is touched:
nothing has ever written this table before this migration exists to create it, and
`app/api/embeds.py`'s own KAN-1741 changes to *use* it land in the same PR, not a follow-up.

Autogenerated against a live Postgres 17 (`COMPOSE_PROJECT_NAME=kaya-kan1741 KAYA_DB_PORT=5441
make db`) and hand-annotated. One correction, the same gap migrations `0007`/`0008` both hit:
autogenerate rendered `user_id`'s column type as `fastapi_users_db_sqlalchemy.generics.GUID()`
without importing the module that name lives in.
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "pandan_link",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("encrypted_token", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kaya_account.id"],
            name=op.f("fk_pandan_link_user_id_kaya_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pandan_link")),
    )
    op.create_index(op.f("ix_pandan_link_user_id"), "pandan_link", ["user_id"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_pandan_link_user_id"), table_name="pandan_link")
    op.drop_table("pandan_link")
