"""device_authorization: RFC 8628 device-flow login

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-26

ADR 0013 (KAN-1743). One additive table, mirroring pandan ADR 0024's shape independently — no
board/workspace picker, since kaya has no board-equivalent entity, so a device-flow-minted
`kaya_pat_…` is always account-wide. See `app/identity/device_flow.py`'s module docstring for the
full "why" (hashing `device_code` with the same `KAYA_AUTH_SECRET` pepper a PAT uses, storing
`user_code` as-is, minting the PAT at first-poll-after-approval rather than at approval time).

**Schema only, same precedent as `0007`/`0008`/`0010`.** No existing route or row is touched:
nothing has ever written this table before this migration exists to create it, and
`app/identity/device_auth.py`'s own changes to *use* it land in the same PR, not a follow-up.

Autogenerated against a live Postgres 17 (`COMPOSE_PROJECT_NAME=kaya-kan1743 KAYA_DB_PORT=5443
make db`) and hand-annotated. One correction, the same gap migrations `0007`/`0008`/`0010` all hit:
autogenerate rendered `user_id`'s column type as `fastapi_users_db_sqlalchemy.generics.GUID()`
without importing the module that name lives in.
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "device_authorization",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_code_hash", sa.String(length=64), nullable=False),
        sa.Column("user_code", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("requested_scope", sa.String(length=16), server_default="write", nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.Column("pat_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requested_scope IN ('read', 'write')",
            name=op.f("ck_device_authorization_requested_scope"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'denied')",
            name=op.f("ck_device_authorization_status"),
        ),
        sa.ForeignKeyConstraint(
            ["pat_id"],
            ["personal_access_token.id"],
            name=op.f("fk_device_authorization_pat_id_personal_access_token"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["kaya_account.id"],
            name=op.f("fk_device_authorization_user_id_kaya_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_authorization")),
        sa.UniqueConstraint("user_code", name=op.f("uq_device_authorization_user_code")),
    )
    op.create_index(
        op.f("ix_device_authorization_device_code_hash"),
        "device_authorization",
        ["device_code_hash"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_device_authorization_device_code_hash"), table_name="device_authorization"
    )
    op.drop_table("device_authorization")
