"""oauth_client table, authorization_code+PKCE columns on device_authorization

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-26

ADR 0014 (KAN-1744). Extends `device_authorization` (migration `0011`) for the browser-redirect
authorization_code+PKCE grant a hosted MCP client (Claude.ai, ChatGPT, Cursor) completes, rather
than a parallel table — the state either grant needs (pending → approved → consumed, expiring,
single-use) is the same shape. See `app/identity/device_flow.py`'s module docstring for the full
kind-split reasoning and `ck_device_authorization_kind`'s exact rule.

Also adds `oauth_client` (RFC 7591 Dynamic Client Registration rows — see
`app/identity/oauth_client.py`; a Client ID Metadata Document client never gets a row here).

**Schema only, same precedent as `0007`/`0008`/`0010`/`0011`.** No existing route or row is
touched: nothing has ever written these columns/this table before this migration exists to create
them, and `app/identity/oauth_authorize_router.py`'s own changes to *use* them land in the same PR.

Autogenerated against a live Postgres 17 (`COMPOSE_PROJECT_NAME=kaya-kan1744 KAYA_DB_PORT=5445
make db`) — no hand corrections needed this time (the `fastapi_users_db_sqlalchemy.generics.GUID`
import gap `0007`/`0008`/`0010`/`0011` all hit doesn't recur here: this migration adds no `GUID`
column).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "oauth_client",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=True),
        sa.Column("redirect_uris", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_client")),
    )
    op.create_index(op.f("ix_oauth_client_client_id"), "oauth_client", ["client_id"], unique=True)

    op.add_column(
        "device_authorization", sa.Column("client_id", sa.String(length=200), nullable=True)
    )
    op.add_column("device_authorization", sa.Column("redirect_uri", sa.String(), nullable=True))
    op.add_column(
        "device_authorization", sa.Column("code_challenge", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "device_authorization",
        sa.Column("code_challenge_method", sa.String(length=16), nullable=True),
    )
    op.add_column("device_authorization", sa.Column("resource", sa.String(), nullable=True))
    op.add_column(
        "device_authorization", sa.Column("code_hash", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "device_authorization",
        "device_code_hash",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "device_authorization", "user_code", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.create_index(
        op.f("ix_device_authorization_code_hash"),
        "device_authorization",
        ["code_hash"],
        unique=True,
    )
    op.create_check_constraint(
        op.f("ck_device_authorization_kind"),
        "device_authorization",
        "(device_code_hash IS NOT NULL AND user_code IS NOT NULL AND client_id IS NULL) OR "
        "(device_code_hash IS NULL AND user_code IS NULL AND client_id IS NOT NULL AND "
        "code_hash IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_device_authorization_kind"), "device_authorization", type_="check")
    op.drop_index(op.f("ix_device_authorization_code_hash"), table_name="device_authorization")
    op.alter_column(
        "device_authorization", "user_code", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    op.alter_column(
        "device_authorization",
        "device_code_hash",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.drop_column("device_authorization", "code_hash")
    op.drop_column("device_authorization", "resource")
    op.drop_column("device_authorization", "code_challenge_method")
    op.drop_column("device_authorization", "code_challenge")
    op.drop_column("device_authorization", "redirect_uri")
    op.drop_column("device_authorization", "client_id")
    op.drop_index(op.f("ix_oauth_client_client_id"), table_name="oauth_client")
    op.drop_table("oauth_client")
